// Verdun World Builder Plugin
// Loads Tier 1 terrain data from JSON and CSV files

#pragma once

#include "CoreMinimal.h"
#include "UObject/NoExportTypes.h"
#include "VerdunTerrainData.h"
#include "VerdunTerrainDataLoader.generated.h"

/**
 * Loads historical terrain data from files
 * Only loads Tier 1 documented data (fort locations, elevations, village positions)
 * Tier 2 and 3 data (crater positions, trench paths) will be generated by artillery system
 */
UCLASS(BlueprintType)
class VERDUNWORLDBUILDER_API UVerdunTerrainDataLoader : public UObject
{
	GENERATED_BODY()

public:
	UVerdunTerrainDataLoader();

	/**
	 * Load terrain parameters from JSON file
	 * @param FilePath Path to terrain_parameters.json
	 * @param OutTerrainData Loaded terrain data
	 * @return True if loaded successfully
	 */
	UFUNCTION(BlueprintCallable, Category = "Verdun|Data Loading")
	static bool LoadTerrainParameters(const FString& FilePath, FVerdunTerrainData& OutTerrainData);

	/**
	 * Load locations database from CSV file
	 * @param FilePath Path to locations_database.csv
	 * @param BattlefieldCenter Center point for coordinate conversion
	 * @param OutLocations Loaded locations with converted world positions
	 * @return True if loaded successfully
	 */
	UFUNCTION(BlueprintCallable, Category = "Verdun|Data Loading")
	static bool LoadLocationsDatabase(const FString& FilePath, const FVerdunBattlefieldCenter& BattlefieldCenter, TArray<FVerdunLocation>& OutLocations);

	/**
	 * Convert geographic coordinates (lat/lon) to Unreal world coordinates
	 * @param Latitude Latitude in degrees
	 * @param Longitude Longitude in degrees
	 * @param ElevationMeters Elevation in meters
	 * @param BattlefieldCenter Battlefield center point
	 * @param Scale Scale multiplier (default 100 for meters to cm)
	 * @return World position in Unreal coordinates (cm)
	 */
	UFUNCTION(BlueprintCallable, Category = "Verdun|Coordinate Conversion")
	static FVector ConvertGeoToWorld(double Latitude, double Longitude, float ElevationMeters, const FVerdunBattlefieldCenter& BattlefieldCenter, float Scale = 100.0f);

	/**
	 * Load complete terrain data package
	 * @param TerrainParamsPath Path to terrain_parameters.json
	 * @param LocationsDBPath Path to locations_database.csv
	 * @param OutTerrainData Complete loaded terrain data
	 * @return True if loaded successfully
	 */
	UFUNCTION(BlueprintCallable, Category = "Verdun|Data Loading")
	static bool LoadCompleteTerrainData(const FString& TerrainParamsPath, const FString& LocationsDBPath, FVerdunTerrainData& OutTerrainData);

private:
	/**
	 * Parse location type from string
	 */
	static EVerdunLocationType ParseLocationType(const FString& TypeString);

	/**
	 * Parse CSV line respecting quoted fields
	 */
	static TArray<FString> ParseCSVLine(const FString& Line);
};
