[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Game/POC_TrenchArtillery/Maps/POC_TrenchArtillery
EditorStartupMap=/Game/POC_TrenchArtillery/Maps/POC_TrenchArtillery
GlobalDefaultGameMode=/Script/OnlyTheDead.VerdunGameMode

[/Script/Engine.GameSession]
MaxPlayers=1

[OnlyTheDead.Game]
GameTitle=Only The Dead
; Battle of Verdun, February 21 - December 18, 1916
BattleStartDate=1916-02-21
BattleEndDate=1916-12-18
TotalBattleDays=303
